### ISSUE TITLE
 type annotation error

### ISSUE THREAD

**Issue by kwoktung** [MetaMask/extension-port-stream#7] opened 2020-12-07 06:33 UTC
```typescript
import PortStream from 'extension-port-stream'

const stream = new PortStream(remotePort) // Ok

function fn(s: PortStream) { // typescript will throw error 'PortStream' refers to a value, but is being used as a type here. Did you mean 'typeof PortStream'?
    // do something 
}
```

**Comment by kwoktung** [comment] 2020-12-15 05:10
please export as es module

**Comment by Gudahtt** [comment] 2021-09-27 13:24
Thanks for the report! I think I see what the problem is. We'll have this fixed in the next release.

**Closed** 2021-10-04 19:32 UTC
